export const campaignFields = [
  ["name", "Campaign Name", "text"],
  ["status", "Delivery", "status"],
  ["objective", "Objective", "text"],
  ["results", "Results", "number"],
  ["resultType", "Result Type", "text"],
  ["costPerResult", "Cost / Result", "money"],
  ["budget", "Budget", "money"],
  ["budgetType", "Budget Type", "text"],
  ["spend", "Amount Spent", "money"],
  ["reach", "Reach", "number"],
  ["impressions", "Impressions", "number"],
  ["frequency", "Frequency", "decimal"],
  ["cpm", "CPM", "money"],
  ["cpp", "Cost / 1K Reached", "money"],
  ["clicks", "Clicks", "number"],
  ["uniqueClicks", "Unique Clicks", "number"],
  ["linkClicks", "Link Clicks", "number"],
  ["ctr", "CTR", "percent"],
  ["linkCtr", "Link CTR", "percent"],
  ["cpc", "CPC", "money"],
  ["costPerLinkClick", "Cost / Link Click", "money"],
  ["landingPageViews", "Landing Page Views", "number"],
  ["costPerLandingPageView", "Cost / LPV", "money"],
  ["contentViews", "Content Views", "number"],
  ["addToCart", "Adds to Cart", "number"],
  ["initiateCheckout", "Checkouts", "number"],
  ["purchases", "Purchases", "number"],
  ["purchaseValue", "Purchase Value", "money"],
  ["purchaseRoas", "Purchase ROAS", "decimal"],
  ["leads", "Leads", "number"],
  ["costPerLead", "Cost / Lead", "money"],
  ["messagingConversations", "Messaging Conversations", "number"],
  ["costPerMessagingConversation", "Cost / Messaging Conversation", "money"],
  ["postEngagements", "Post Engagements", "number"],
  ["pageEngagements", "Page Engagements", "number"],
  ["videoViews", "Video Views", "number"],
  ["reactions", "Reactions", "number"],
  ["comments", "Comments", "number"],
  ["saves", "Saves", "number"],
  ["searches", "Searches", "number"],
  ["addPaymentInfo", "Payment Info Added", "number"],
  ["registrations", "Registrations", "number"],
  ["conversions", "Conversions", "number"],
  ["cpa", "CPA", "money"],
].map(([key, label, type]) => ({ key, label, type }));
export const summableCampaignFields = new Set([
  "results",
  "budget",
  "spend",
  "reach",
  "impressions",
  "clicks",
  "uniqueClicks",
  "linkClicks",
  "landingPageViews",
  "contentViews",
  "addToCart",
  "initiateCheckout",
  "purchases",
  "purchaseValue",
  "leads",
  "messagingConversations",
  "postEngagements",
  "pageEngagements",
  "videoViews",
  "reactions",
  "comments",
  "saves",
  "searches",
  "addPaymentInfo",
  "registrations",
  "conversions",
]);

const metricColors = ["#2563eb", "#06b6d4", "#8b5cf6", "#22b982", "#ff536b"];
const preciseMoneyKeys = new Set([
  "costPerResult",
  "cpm",
  "cpp",
  "cpc",
  "costPerLinkClick",
  "costPerLandingPageView",
  "costPerLead",
  "costPerMessagingConversation",
  "cpa",
]);
const paidAnalyticsKeys = new Set([
  "spend",
  "reach",
  "impressions",
  "frequency",
  "clicks",
  "uniqueClicks",
  "linkClicks",
  "ctr",
  "linkCtr",
  "cpc",
  "cpm",
  "cpp",
  "costPerLinkClick",
  "landingPageViews",
  "costPerLandingPageView",
  "contentViews",
  "addToCart",
  "initiateCheckout",
  "purchases",
  "purchaseValue",
  "purchaseRoas",
  "leads",
  "costPerLead",
  "messagingConversations",
  "costPerMessagingConversation",
  "postEngagements",
  "pageEngagements",
  "videoViews",
  "reactions",
  "comments",
  "saves",
  "searches",
  "addPaymentInfo",
  "registrations",
  "results",
  "costPerResult",
  "conversions",
  "cpa",
]);
export const paidAnalyticsMetricOptions = campaignFields
  .filter((field) => paidAnalyticsKeys.has(field.key))
  .map((field, index) => ({
    ...field,
    color: metricColors[index % metricColors.length],
    money: field.type === "money",
    maximumFractionDigits: preciseMoneyKeys.has(field.key) ? 2 : 0,
    percent: field.type === "percent",
    decimal: field.type === "decimal",
  }));
